### ISSUE TITLE
Document that lines are one-based and columns are zero based.

### ISSUE THREAD

**Issue by johnjbarton** [mozilla/source-map#118]
The source map spec v3 uses zero based lines:

```
the zero-based starting line in the original source
```

The readme here does not say but evidently this library uses one-based lines:
https://github.com/mozilla/source-map/blob/master/lib/source-map/source-map-consumer.js#L277

It would be helpful if the readme was clear on this point.

**Comment by carlsmith** [comment]
+1 This tripped me up. V8 uses 1 based lines and columns. It's a bit of a mess.

**Comment by fitzgen** [comment]
This lib matches the spec, but it would be best if everything was 1-based, as that is what all major browsers use for `Error.prototype.stack`.

That said, PRs are of course welcome for doc updates.

**Comment by carlsmith** [comment]
Looking at the spec linked to to in the README for this project, it looks like it uses zero-based everything, which CoffeeScript's source maps also use. This lib uses one-based lines and zero-based columns, and browsers are just one-based. I've no idea what other projects do, but it seems better to put this information somewhere central (bottom of the the spec?), than in this projects README.

**Comment by samuelkaufman** [comment]
Hey so [Chrome is zero based now[1] as far as devtools is concerned. I'm not entirely sure when it changed but I think from Chromium 54.
I can't track down why or really when, but [here][2] is a clue.

I noticed because my [tool][3] that translates Chrome stack traces via this lib started barfing about line zero.

[1]: https://chromium.googlesource.com/v8/v8.git/+/master/src/inspector/js_protocol.json#173
[2]: https://chromium.googlesource.com/chromium/src.git/+/6667812b2dffe3f6bf794b2b040504e5a3ad7cb7%5E!/
[3]: https://www.bugreplay.com

**Comment by tromey** [comment]
I also was confused by the 1-based lines and 0-based columns.  I'll send a PR to update the documentation.
