### ISSUE TITLE
Try an iterative merge sort instead of recursive quick sort

### ISSUE THREAD

**Issue by fitzgen** [mozilla/source-map#187]
![screen shot 2015-06-26 at 2 33 52 pm](https://cloud.githubusercontent.com/assets/74571/8387828/a2291fde-1c10-11e5-8d3c-7ffdba5141ec.png)

so much baseline wow

Working theory:

enter quick sort in baseline -> quick sort gets hot enough for ion -> don't compile loop head entry points -> old frames never leave baseline and enter ion

**Comment by fitzgen** [comment]
cc @ejpbruel @kannanvijayan

**Comment by ejpbruel** [comment]
I'm not sure how to interpret that graph. So is iterative sorting faster or
not?

**Comment by kannanvijayan** [comment]
Each bar in the graph is a bucket containing the number of samples gathered during that time period.  It's colored based on the number of samples that were made in Ion (green) vs Baseline (blue) vs Interpreter (red).

The graph is basically showing that the majority of samples grabbed for the doQuickSort function are in baseline.  This means that the majority of the time we're spending in doQuickSort, is happening in baseline.

The question is why.  The hypothesis is that we recurse down in baseline, and optimize the function with Ion near the bottom of the tree, but higher on up the frames are still in baseline.  As we go back up and down the tree, we catch baseline frames higher up that have not yet been converted to Ion.

I've been thinking about this and talking about it with @fitzgen, and there's definitely something confusing about this.  Even if the callers higher up the recursive sort are in baseline, the quicksort does all of its heavyweight work BEFORE it recurses.  Which means that we shouldn't spend a lot of time in the caller when we return back up the sort recursion.  At most, we'll return up, and immediately call into a recursive right-hand sort (which should enter into an Ion-compiled function).

Today is a holiday in Canada but I'm going to look more closely at what's happening here.  @fitzgen updated the code to generate shell tests, so I'm going to use that with the spidermonkey shell to try to get at why we're getting so many baseline samples.

**Comment by fitzgen** [comment]
By the way, @kannanvijayan, the updates with the latest speed ups from JIT profiling and being able to run the benchmark in the shell landed on master earlier today. You no longer need to work off of my branch.

**Comment by kannanvijayan** [comment]
Cool.  Also, your delta patches for the jit coach got my build showing the mountain range graphs again.  I ran a quick test of some modified doQuickSort code I was playing with, and got this:
http://imgur.com/qOqQVgY

This is the modified doQuickSort I used to get that:

https://pastebin.mozilla.org/8838299

Not entirely sure if it's correct, but the major modifications:

1. For regions of size 2, do a manual check and swap instead of recursing in.
2. Left the right-hand-side of the quicksort recursion into a top-level loop.  Basically manual tail-call elimination for the second recursive call to doQuickSort.

That said, measuring the perf gains empirically, it doesn't seem to have THAT big of an effect to have the sort run entirely in Ion.

**Comment by fitzgen** [comment]
Interesting, that doesn't provide a speedup when running the benchmark?

Would also be interested in seeing a proper insertion sort when the array < 100 (say)

**Comment by kannanvijayan** [comment]
Yeah.  The perf improvements, if any, did not show up in the variation noise in the time measurements of each run.  It might not be that big of a deal.  3s to parse a 16MB source-map file is not that bad.  I think using a custom allocator and allocating the Mapping objects inside a TypedArray, then keeping the sorted indexes as separate typed-arrays holding indexes into the first typed-array, would likely be the biggest win.  Skip the GCs, memory usage is a lot tighter - each Mapping will be a variable-length run of uint32s in a typed-array.  The quicksort swaps will be uint32 swaps instead of value swaps.  Also, the quicksort array swaps will additionally not incur a write barrier overhead.

Also, moving the entire parse to a typed array should help with offloading the processing to a worker.  Send in a movable typed array to the worker, and the worker moves back three typed arrays: the mappings typed array, and the 2 indexing typed arrays.

What do you think?

Also, this gives me a another thought as to things we need to instrument: gc write barriers.

**Comment by fitzgen** [comment]
> Also, moving the entire parse to a typed array should help with offloading the processing to a worker.

Unfortunately, the debugger has to make decisions now and not later (such as whether to pause the debuggee or not) based on information in source maps, so putting this off in a worker is a non-starter :(

**Comment by fitzgen** [comment]
> allocating the Mapping objects inside a TypedArray

Yup, see https://github.com/mozilla/source-map/issues/161. It's just a bit more invasive of a change, and so no one has found time to get to it yet.

**Comment by kannanvijayan** [comment]
Couldn't we do the translation eagerly when breakpoints are set?  I.e. when a breakpoint is set in the original source, the debugger immediately maps it to target js location info.  Then later it doesn't need to go through the source map to check if it needs to break etc.

**Comment by fitzgen** [comment]
That situation isn't the one that leads to behavior that requires immediate source map knowledge, and that is pretty much how we handle things now.

There are two cases that do require :

1. *Refreshing* (or any re-introduction of the "same" script with an updated source map) with breakpoints already set in the old version of the source mapped source, We have to parse the new source map to find the correct generated lines and bytecode offsets to set breakpoints upon. This has to be done now, not later, or else we can't hit breakpoints set in top level scripts.

2. When stepping or errors are thrown, etc we need to check if the original/authored source is "black boxed" by the user, meaning that they want to step "through" it because it is some 3rd party lib or a minified thing, etc.

**Comment by jkrems** [comment]
I'm closing these issues (#187 and #189) since acting on anything here will likely require going back to profiling, given the changes to the code that happened in the past few years.
