### ISSUE TITLE
Error in 0.4.3: "0" is not in the set.

### ISSUE THREAD

**Issue by ai** [mozilla/source-map#191]
I update source-map in PostCSS to 0.4.3 and got a errors in tests on `map.toString()`

```
Error: "0" is not in the set.
```

/cc @fitzgen

**Comment by ai** [comment]
Very strange, error is reproduced if I create a Consumer froom Generator and then all `toJSON()` on generator.

**Comment by ai** [comment]
Yu can reproduce error by:

```js
var sourceMap = require('source-map');

var generator = new sourceMap.SourceMapGenerator({ file: 'a.css' });
generator.addMapping({
    source:   'b.css',
    original: {
        line:   1,
        column: 0
    },
    generated: {
        line:   1,
        column: 0
    }
});

// If you comment one of this lines, everything will be OK
var consumer  = sourceMap.SourceMapConsumer.fromSourceMap(generator);
generator.toJSON();
```

**Comment by fitzgen** [comment]
I suspect this is fallout from https://github.com/mozilla/source-map/commit/93f411cf2a3d6af2e280c4f6605ced6de8efd692

**Comment by ben-eb** [comment]
I narrowed down the problem to here: https://github.com/mozilla/source-map/blob/master/lib/source-map/array-set.js#L77-L82

Replacing the `throw` with `return 0` passes all PostCSS tests, but of course it is a naive 'fix'. I think the indexOf should be able to handle `0` as well rather than throwing.

**Comment by fitzgen** [comment]
Ok, so what is happening is that after 93f411c, we are internally storing the index of the source rather than the source string itself.

When creating a SourceMapConsumer from a SourceMapGenerator, we are copying the array of mappings over, but end up sharing the same mapping objects that are entries in the arrays. When we modify those mapping objects to use indices instead of the source strings, that ends up mutating state that is shared with the old SourceMapGenerator.

We can copy the entries so that we don't share state, but that will end up killing a lot of the performance gains that this method gives over `new SourceMapConsumer(mySourceMapGenerator.toJSON())`. We could make a new method (so that this one can remain backwards compatible) which explicitly takes ownership of the old SourceMapGenerator and makes any further operations on it throw an error with a message like "this SourceMapGenerator is no longer valid, it was converted into a SourceMapConsumer" or something.

Will whip up a patch for the first part in a second.

**Comment by fitzgen** [comment]
I suppose a better solution would be to give SourceMapGenerator the same optimization we gave SourceMapConsumer, and then we could go back to safely sharing state since it would all be immutable.

**Comment by fitzgen** [comment]
> I suppose a better solution would be to give SourceMapGenerator the same optimization we gave SourceMapConsumer, and then we could go back to safely sharing state since it would all be immutable.

Fied #195 for this.

**Comment by ai** [comment]
OK, I am waiting for release, because my tests are failing right now.

**Comment by fitzgen** [comment]
I will make a release as soon as we merge #194 later today.

**Comment by fitzgen** [comment]
> OK, I am waiting for release, because my tests are failing right now.

Release 0.4.4 is published.
