### ISSUE TITLE
originalPositionFor 's result is null  when using babel loader

### ISSUE THREAD

**Issue by xiachaoxulu** [mozilla/source-map#274]
here is a demo
please have a look
https://github.com/xiachaoxulu/sourceMapDemo

**Comment by tromey** [comment]
That test is looking for the mapping at line 141, column 0.  When I dump the source map, though, I see this entry for that line:
```
   column 18
   source #3
   orig line 14
   orig column 0
```
That is, there is no mapping at column 0.  So returning `null` is correct, because the default search mode is `GREATEST_LOWER_BOUND`.

If I change the call to use `LEAST_UPPER_BOUND`, I get
```
{ source: 'webpack:///hello.vue',
  line: 15,
  column: 0,
  name: null }
```

So I don't think there is a bug here.

**Comment by tromey** [comment]
Also - I forgot to mention, but thank you for the test case.  It was very clear.

**Comment by xiachaoxulu** [comment]
Thank you.  I find the search mode a few days ago. So i already konw the reason. But i forget closed this issue. I am sorry.
In fact . The sourcemap which Babel generate  is incorrect . Sometimes the  mapping  is wrong.
So this is not yours issue. It belongs to babel
But they don't seem to have any good solutions
