### ISSUE TITLE
Broken util.js in v0.7.0

### ISSUE THREAD

**Issue by krulls** [mozilla/source-map#318]
Getting this when building with Gulp while depending on [gulp-sourcemaps 1.7.1](https://github.com/gulp-sourcemaps/gulp-sourcemaps/tree/v1.7.1):

````
09:48:01 /path/to/my/nodejs/project/node_modules/gulp-sourcemaps/node_modules/source-map/lib/util.js:94
09:48:01       input,
09:48:01            ^
09:48:01 SyntaxError: Unexpected token ,
09:48:01     at Module._compile (module.js:439:25)
09:48:01     at Object.Module._extensions..js (module.js:474:10)
09:48:01     at Module.load (module.js:356:32)
09:48:01     at Function.Module._load (module.js:312:12)
09:48:01     at Module.require (module.js:364:17)
09:48:01     at require (module.js:380:17)
09:48:01     at Object.<anonymous> (/path/to/my/nodejs/project/node_modules/gulp-sourcemaps/node_modules/source-map/lib/source-map-generator.js:9:12)
09:48:01     at Module._compile (module.js:456:26)
09:48:01     at Object.Module._extensions..js (module.js:474:10)
09:48:01     at Module.load (module.js:356:32)
````

The error raised 7 days ago -> the time you released 0.7.0.

This is critical since all gulp-sourcemaps versions I saw reference a "0.x" version.

**Comment by fitzgen** [comment]
Thanks for filing an issue.

It looks like the node version you're running doesn't support modern ECMAScript's object literal short hands. We require node >= 8: https://github.com/mozilla/source-map/blob/master/package.json#L57

> This is critical since all gulp-sourcemaps versions I saw reference a "0.x" version.

`gulp-sourcemaps` should specify `^0.6` or something similar, if it wants to depend only on a non-breaking series, since below 1.0.0, a 0.x version bump is considered a breaking change.
