### ISSUE TITLE
dist/test is not being generated

### ISSUE THREAD

**Issue by Standard8** [mozilla/source-map#348]
According to the source-map upgrading document in mozilla-central:

```
    $ npm install
    $ npm run-script build  -or-  nodejs Makefile.dryice.js (if you have issues with npm)
    $ cp dist/source-map.js /path/to/mozilla-central/devtools/shared/sourcemap/source-map.js
    $ cp dist/test/* /path/to/mozilla-central/devtools/shared/sourcemap/tests/unit/
```

Unfortunately, when I checked out latest master, the last command is failing because dist/test/* isn't generated. I took a brief look through the commit messages but couldn't see any obvious reason.

**Comment by jkrems** [comment]
Is this still causing issues?

**Comment by ochameau** [comment]
dist folder has been removed in #362.

As of today, mozilla-central pulls the source-map package via npm from here:
https://searchfox.org/mozilla-central/rev/d416a7b827c2d76b12848e355a4e03dde49ece25/devtools/client/debugger/packages/devtools-source-map/package.json#24
(Note that I'll probably revisit this way of vendoring the source-map package)

So I believe this issue is now invalid. The package is meant to be used as is, as a node package and not longer use webpack itself.
If you need to build a bundle you should do that outside of this repo to avoid pulling webpack as a dependency.
