### ISSUE TITLE
The latest version of IE11 does not work with the error "polyfill-eventsource added missing eventsource to window"

### ISSUE THREAD

**Issue by FreeDemons** [mozilla/source-map#388]
Currently, it cannot be run on IE11. The error message is "polyfill-eventsource added missing eventsource to window".

**Comment by jkrems** [comment]
This could be related to the whatwg-url polyfill but I'm not sure. Adding triage label.

**Comment by ochameau** [comment]
> Currently, it cannot be run on IE11. The error message is "polyfill-eventsource added missing eventsource to window".

As said over https://github.com/webpack-contrib/webpack-hot-middleware/issues/53, this is only a warning message and not really an error.

Were you having any other exception?

Otherwise IE11 has been fully deprecated Jun 2022:
https://blogs.windows.com/windowsexperience/2022/06/15/internet-explorer-11-has-retired-and-is-officially-out-of-support-what-you-need-to-know/

May be we could close this as won't fix.

**Comment by eemeli** [comment]
Closing as IE11 is no longer supported.
