### ISSUE TITLE
Method for `allOriginalPositionsFor`

### ISSUE THREAD

**Issue by connor4312** [mozilla/source-map#416]
We have a method `allGeneratedPositionsFor`, it would be useful to have a similar method `allOriginalPositionsFor`.

**Comment by loganfsmyth** [comment]
Generally with sourcemaps there would only be a single original position for a given generated position, otherwise for instance if a stack trace contains a JS engine position, or a debugger pauses at a given location in the generated code, there would be no way to know what original position to use when converting from generated to original.

**Comment by connor4312** [comment]
Yea, you're right. I was deep in debugging some weird sourcemap stuff and forgot which was way up 😄
