### ISSUE TITLE
Please adopt (standard) semantic version numbers.

### ISSUE THREAD

**Issue by johnjbarton** [mozilla/source-map#428]
Unexpected breaking changes in v0.7.0 broke karma-runner https://github.com/karma-runner/karma/issues/3557

https://docs.npmjs.com/about-semantic-versioning#incrementing-semantic-versions-in-published-packages

**Comment by loganfsmyth** [comment]
This does follow semver, otherwise npm would have seen `^0.6.1` in karma's `package.json` and installed `0.7.3` as the most recent matching version. Packages beginning in `0.x` essentially treat their second (`x`) digit as the major version number, so these breaking changes are exactly what made the package go from `0.6` to `0.7`.

**Comment by jkrems** [comment]
I think the original question has been addressed.
