### ISSUE TITLE
Wrong sourceRoot handling?

### ISSUE THREAD

**Issue by sokra** [mozilla/source-map#62]
From the spec:

> Line 4: An optional source root, useful for relocating source files on a server or removing repeated values in the “sources” entry.  This value is prepended to the individual entries in the “source” field.

The spec say that the `sourceRoot` is **prepended**, but mozilla/source-map concat it with an additional slash `/`.

**Comment by tromey** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=977463#c10.  What Chrome does is:
```
    var sourceRoot = sourceMap.sourceRoot || '';
    if (sourceRoot && !sourceRoot.endsWith('/'))
      sourceRoot += '/';
    for (var i = 0; i < sourceMap.sources.length; ++i) {
      var href = sourceRoot + sourceMap.sources[i];
      var url = Common.ParsedURL.completeURL(this._sourceMappingURL, href) || href;
```

I tend to think this library should do this as well.  Also, it seems to me that it would be good for `SourceMapConsumer` to take the source map URL as a parameter, so this computation can be done by the library, and not by the consumers.  I already had to work around this problem in the devtools-source-map in order to get some existing code working.

**Comment by tromey** [comment]
If you're still following this issue, I encourage you to look at the PR.

**Comment by tromey** [comment]
Well, that PR didn't work out.  It tried to cut a corner but that can't work.

It's possible not to cut corners, and implement what the spec says.  However this affects the API quite a bit.

My first idea was to only keep absolute source URLs.  But, there are tests that indicate that users of the API expect to be able to look up relative URLs; for example the test for issue #64.

Maybe a more complicated idea is possible: keep the storage as-is, and absolutize URLs when handing them out -- but then `sourceContentFor` has to try to look the URL up twice.
